name: Generate WP Self-Host JSON
on:
  push:
    branches:
      - main
jobs:
  generate-json-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run WP Self-Host Update JSON Generator
        uses: eduardovillao/wp-self-host-json-generator@main